// <auto-generated />
namespace GameStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update30PW : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update30PW));
        
        string IMigrationMetadata.Id
        {
            get { return "201801310159439_Update3.0PW"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
