// <auto-generated />
namespace GameStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Dodanie_OrRecommended_Do_Gamecs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dodanie_OrRecommended_Do_Gamecs));
        
        string IMigrationMetadata.Id
        {
            get { return "201801301951427_Dodanie_OrRecommended_Do_Game.cs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
