// <auto-generated />
namespace GameStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update23HK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update23HK));
        
        string IMigrationMetadata.Id
        {
            get { return "201801302053386_Update2.3HK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
