// <auto-generated />
namespace GameStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update29PW : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update29PW));
        
        string IMigrationMetadata.Id
        {
            get { return "201801310156524_Update2.9PW"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
